apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: cost
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        path:
          name: src
        repository: costdev
        revision: costdev
      systemToGitSync: true
    name: cost1
    type: SystemSync
  triggers:
  - config:
      repo:
        provider: Github
        repository: costdev
        revision: costdev
    name: costdevtrig
    type: Webhook
