apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: testpipeline
  project: defaultproject
spec:
  active: false
  sharing:
    enabled: false
  stages:
  - config:
      approvers:
      - userName: raghavendra@rafay.co
      timeout: 0s
      type: Email
    name: stage-01
    preConditions:
    - config: costmgmt-testing
      type: Expression
    - config: costmgmt-dasboard
      type: Expression
    type: Approval
