apiVersion: servicemesh.k8smgmt.io/v3
kind: ClusterMeshPolicy
metadata:
  name: gittest
  project: defaultproject
spec:
  rules:
  - name: enable-strict-mtls
    version: version-1665658202
  version: v1
