apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: costmgmt-demo
  project: defaultproject
spec:
  blueprintConfig:
    name: costmgmt-demo
    version: v3
  cloudCredentials: raghavendra
  config:
    metadata:
      name: costmgmt-demo
      region: us-west-2
      version: "1.22"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: Ubuntu2004
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          externalDNS: true
          imageBuilder: true
      instanceType: t2.xlarge
      maxSize: 2
      minSize: 2
      name: costmgmt-demo
      ssh:
        allow: true
        publicKeyName: raghavendra-keypair
      version: "1.22"
      volumeSize: 40
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
