apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: costtest
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDg8vCtScZ3NZWuwlNKmRVKf0XvfdY0KFPlEqf21tXH6w/N19Tryqm8BXVAn24sCqfqC0FfeTC7hDxQXK4MrSp679KP0xG/W8ufw/RSj5uTZ/Zj/SKvzJgaZhF/wKvO5NTCop2MWdmuYygPwXC/9Pg2Wgh+RuNWMviU0n7UQO0rsX3Zd55N5DhD/f+o35rirCMAqC2fDcnrh3z9KOdtYJ7jAUzMVDxzthERFT/2FANNAL/HiEhA6JE9qD42YcrDn3SjMlfP7E1/wJWYrHQPbsBJ43oitFC4ilFxzlzkspohiJerjQBBVGnl2x9So9e2y0VmllIcP00kslCznAFHdSZYf2i+5rCzOKy5AiRKaZib3KqnJA+B+fe4qKpr4CWV+KTdk3+WXhPBokYQ6bYlyeakI9/A+SZ6o5M=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: costtest
      namespace: default

