apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: ctcp1
  project: defaultproject
spec:
  installationParams:
    aws:
      awsCredentials:
        awsAccountId: awsAccId
        awsServiceKeyName: DFGF
      curIntegration:
        athenaBucketName: reserved-pricing
        athenaDatabase: rafay
        athenaRegion: us-west-1
        athenaTable: costmgmt
      spotIntegration:
        awsSpotDataBucket: spot-pricing
        awsSpotDataPrefix: costmgmt
        awsSpotDataRegion: us-west-1
        spotLabel: ctype3
        spotLabelValue: cspot
  providerType: AWS
  sharing:
    enabled: false
  version: v1
