apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: st
  project: defaultproject
spec:
  installationParams:
    aws:
      awsCredentials: {}
      curIntegration: {}
      spotIntegration: {}
  providerType: aws
  sharing: {}
  version: v1
