apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: systogit
  project: defaultproject
spec:
  installationParams:
    aws:
      awsCredentials:
        awsAccountId: "121212"
        awsServiceKeyName: 111s
      curIntegration: {}
      spotIntegration:
        awsSpotDataBucket: sd
        awsSpotDataPrefix: sd
        awsSpotDataRegion: d
        spotLabel: sdf
        spotLabelValue: sdf
  providerType: aws
  sharing:
    enabled: false
  version: v1
