apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: t1
  project: defaultproject
spec:
  installationParams:
    aws:
      awsCredentials: {}
      curIntegration:
        athenaBucketName: c
        athenaRegion: c
      spotIntegration:
        spotLabel: a
        spotLabelValue: v
  providerType: aws
  sharing:
    enabled: false
  version: v1
