apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: test2aws
  project: defaultproject
spec:
  installationParams:
    aws:
      curIntegration:
        athenaBucketName: khjh
        athenaRegion: jkhkh
      spotIntegration:
        awsSpotDataRegion: dsa
        spotLabel: "12"
        spotLabelValue: "32"
  providerType: AWS
  sharing:
    enabled: true
    projects:
    - name: testproj1
    - name: testprojec
  version: v1
