apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gittosys1
  project: defaultproject
spec:
  base:
    name: default
    version: 1.18.0
  costProfileRef: {}
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableIngress: false
    enableLogging: false
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  networkPolicy: {}
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  type: custom
  version: v5
