apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: nbp1
  project: defaultproject
spec:
  base:
    name: default
    version: 1.19.3
  costProfileRef:
    enabled: true
    name: cp1
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableIngress: true
    enableLogging: false
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  meshRef: {}
  networkPolicy: {}
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  type: custom
  version: v1
