apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: opcp1
  project: defaultproject
spec:
  base:
    name: default
    version: 1.19.6
  costProfileRef:
    enabled: true
    name: opcp
    version: v1
  defaultAddons:
    enableMonitoring: true
  type: custom
  version: v1
