apiVersion: servicemesh.k8smgmt.io/v3
kind: MeshProfile
metadata:
  name: test
  project: defaultproject
spec:
  installationParams:
    resourceQuota:
      cpuRequests: 500m
      memoryRequests: 2048Mi
  sharing:
    enabled: true
    projects:
    - name: '*'
  version: v1
